# Generated by Django 5.2.14 on 2026-06-15 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadiaria',
            options={'ordering': ['-data'], 'verbose_name': 'Meta Diaria', 'verbose_name_plural': 'Metas Diarias'},
        ),
        migrations.AddField(
            model_name='metadiaria',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Meta'),
        ),
        migrations.AddField(
            model_name='metadiaria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário'),
        ),
    ]
